HereToYou/Controllers/AdminController.cs
using HereToYou.Context;
using HereToYou.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HereToYou.Controllers
{
    public class AdminController : Controller
    {
      
        
            private readonly MyContext _context;
            public AdminController(MyContext myContext)
            {
                _context = myContext;
            }
        public async Task<IActionResult> Index()
        {
            // Check if the user is authenticated and has the required role
            if (HttpContext.Session.GetInt32("userId") != null && HttpContext.Session.GetInt32("RoleId") == 1)
            {
                // Fetch data from the database
                var totalSale = _context.Orders.Sum(p => p.TotalAmount);
                var productsCount = _context.Products.Count();
                var userCount = _context.Users.Count();
                var yesterday = DateTime.Today.AddDays(-1).Date;
                var today = DateTime.Today.Date.AddDays(1).AddTicks(-1);

                var lastDaySales = _context.Orders
                    .Where(p => p.CreatedAt >= yesterday && p.CreatedAt <= today)
                    .Sum(p => (decimal?)p.TotalAmount) ?? 0;

                // Fetch contact messages
                var contactMessages = await _context.ContactUsMessages
                    .Select(c => new ContactUs
                    {
                        ContactUsId = c.ContactUsId,
                        Name = c.Name,
                        Email = c.Email,
                        Subject = c.Subject,
                        Message = c.Message,
                        DateSubmitted = c.DateSubmitted,
                    })
                    .ToListAsync();

                // Store data in ViewBag or ViewData
                ViewBag.Name = HttpContext.Session.GetString("name");
                //ViewBag.Image = HttpContext.Session.GetString("image");
                ViewBag.TotalSale = totalSale;
                ViewBag.ProductsCount = productsCount;
                ViewBag.UserCount = userCount;
                ViewBag.LastDaySales = lastDaySales;

                // Pass the contact messages to the view using ViewData
                ViewData["ContactMessages"] = contactMessages;

                return View();
            }
            else
            {
                return RedirectToAction("Login", "Authentication");
            }
        }

        public async Task<IActionResult> Product()
        {
            if (HttpContext.Session.GetInt32("userId") != null && HttpContext.Session.GetInt32("RoleId") == 1)
            {
                var myContext = _context.Products.Include(p => p.Category);
                return View(await myContext.ToListAsync());
            }
            else
            {
                return RedirectToAction("Login", "authentication");


            }
            return View();
        }
        public async Task<IActionResult> Category()
        {
            if (HttpContext.Session.GetInt32("userId") != null && HttpContext.Session.GetInt32("RoleId") == 1)
            {
                var myContext = _context.Categories;
                return View(await myContext.ToListAsync());
            }
            else
            {
                return RedirectToAction("Login", "authentication");
            }
            return View();
        }

        public async Task<IActionResult> Order()
        {
            if (HttpContext.Session.GetInt32("userId") != null && HttpContext.Session.GetInt32("RoleId") == 1)
            {
                var myContext = _context.OrderItems
                                    .Include(oi => oi.Order)         // Include the Order entity related to OrderItem
                                        .ThenInclude(o => o.User)   // Include the User entity related to Order
                                    .Include(oi => oi.Product)       // Include the Product entity related to OrderItem
                                    .ToListAsync();                  // Execute the query

                var orderItems = await myContext;

                return View(orderItems);
            }
            else
            {
                return RedirectToAction("Login", "authentication");
            }
            return View();
        }


    }
    }

HereToYou/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HereToYou.Context;
using HereToYou.Models;

namespace HereToYou.Controllers
{
    public class OrdersController : Controller
    {
        private readonly MyContext _context;

        public OrdersController(MyContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var myContext = _context.Orders.Include(o => o.User);
            return View(await myContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,TotalAmount,CreatedAt,Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,TotalAmount,CreatedAt,Status")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'MyContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

HereToYou/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HereToYou.Context;
using HereToYou.Models;

namespace ecommerce.Controllers
{
    public class UsersController : Controller
    {

        private readonly MyContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public UsersController(MyContext context, IWebHostEnvironment webHostEnvironment)
        {

            _context = context;
            this.webHostEnvironment = webHostEnvironment;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {

            ViewBag.name = HttpContext.Session.GetString("name");
            var myContext = _context.Users.Include(u => u.Role);
            return View(await myContext.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {

            //ViewBag.name = HttpContext.Session.GetString("name");
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create
            ([Bind("Id,Username,PasswordHash,Email,Location,phoneNumber,RoleId")] User user)
        {
           
            _context.Add(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
            Edit(int id, [Bind("Id,Username,PasswordHash,Email,Location,phoneNumber,RoleId,Birthday")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }


            try
            {
                
                _context.Update(user);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(user.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'MyContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return (_context.Users?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> SearchByUserName(string? name)
        {
            var user = _context.Users.Include(r => r.Role).AsQueryable();

            if (!string.IsNullOrEmpty(name))
            {
                user = user.Where(u => u.Username.Contains(name));
            }

            var users = await user.ToListAsync();


            return View("Index", users);
        }


    }
}

HereToYou/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>DarkPan - Bootstrap 5 Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/AdminAsseets/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/AdminAsseets/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/AdminAsseets/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/AdminAsseets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/AdminAsseets/css/style.css" rel="stylesheet">
</head>
<style>
    .primary {
        color: #ffffff !important; /* or any other blue shade you prefer */
        background-color: #ffffff !important;
    }

    /* Update other elements that use the red color */
    .navbar-dark .navbar-nav .nav-link {
        color: #ffffff !important;
    }

    .alert-primary {
        background-color: #ffffff !important;
        border-color: #ffffff !important;
    }

    .progress-bar.progress-bar-striped.bg-primary {
        background-color: #ffffff !important;
    }

    /* Set all Font Awesome and Bootstrap Icons to white */
    .fa, .bi {
        color: #ffffff !important;
    }

    /* Specific to Sidebar */
    .sidebar .nav-item .nav-link .fa,
    .sidebar .nav-item .nav-link .bi {
        color: #ffffff !important;
    }

    /* Specific to Navbar */
    .navbar .nav-item .nav-link .fa,
    .navbar .nav-item .nav-link .bi {
        color: #ffffff !important;
    }
</style>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a href="index.html" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-user-edit me-2" ></i>HereToYou</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">@ViewBag.name</h6>
                        <span style="font-weight:700; color:#EB1616">Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a asp-action="Index" asp-controller="Admin" class="nav-item nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Admin" ? "active" : "")">
                        <i class="fa fa-tachometer-alt me-2"></i>Dashboard
                    </a>
                    <a asp-action="Index" asp-controller="Categories" class="nav-item nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Categories" ? "active" : "")">
                        <i class="fa fa-th me-2"></i>Categories
                    </a>
                    <a asp-action="Index" asp-controller="Products" class="nav-item nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Products" ? "active" : "")">
                        <i class="fa fa-th me-2"></i>Products
                    </a>
                    <a asp-action="Index" asp-controller="Orders" class="nav-item nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Orders" ? "active" : "")">
                        <i class="fa fa-keyboard me-2"></i>Orders
                    </a>
                    <a asp-action="Index" asp-controller="Users" class="nav-item nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Users" ? "active" : "")">
                        <i class="fa fa-table me-2"></i>User
                    </a>
                    @* <a asp-action="Index" asp-controller="Testimonials" class="nav-item nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "Testimonials" ? "active" : "")">
                        <i class="fa fa-table me-2"></i>Testimonials
                    </a> *@
                    <a asp-action="Index" asp-controller="ContactUs" class="nav-item nav-link @(ViewContext.RouteData.Values["controller"].ToString() == "ContactUs" ? "active" : "")">
                        <i class="fa fa-table me-2"></i>Contact Us
                    </a>
                </div>

            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars text-white"></i>
                </a>
                <form class="d-none d-md-flex ms-4">
                    <input class="form-control bg-dark border-0" type="search" placeholder="Search">
                </form>
                <div class="navbar-nav align-items-center ms-auto">
                    <!-- Message dropdown -->
                    <div class="nav-item dropdown me-3">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-envelope text-white me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex text-white">Message</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small class="text-muted">15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small class="text-muted">15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small class="text-muted">15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all message</a>
                        </div>
                    </div>

                    <!-- Notification dropdown -->
                    <div class="nav-item dropdown me-3">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell text-white me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex text-white">Notificatin</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small class="text-muted">15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small class="text-muted">15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small class="text-muted">15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>

                    <!-- User dropdown -->
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <span class="d-none d-lg-inline-flex text-white">@ViewBag.name</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a class="dropdown-item" asp-action="Logout" asp-controller="authentication">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>

            @RenderBody()
        </div>
        <!-- Content End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/AdminAsseets/lib/chart/chart.min.js"></script>
    <script src="~/AdminAsseets/lib/easing/easing.min.js"></script>
    <script src="~/AdminAsseets/lib/waypoints/waypoints.min.js"></script>
    <script src="~/AdminAsseets/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/AdminAsseets/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/AdminAsseets/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/AdminAsseets/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/AdminAsseets/js/main.js"></script>
</body>
</html>