HereToYou/Models/Category.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace HereToYou.Models
{
	public class Category
	{
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [MaxLength(255)]
        public string Name { get; set; }
        [MaxLength(255)]
        public string Description { get; set; }
        public ICollection<Product> Products { get; set; }
    }
}

HereToYou/Models/Order.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace HereToYou.Models
{
    public class Order
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int? UserId { get; set; }
        [ForeignKey("UserId")]
        public User User { get; set; }
        public decimal TotalAmount { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        [MaxLength(50)]
        public string Status { get; set; }//'Pending', 'Completed', 'Cancelled'

        public ICollection<OrderItem> OrderItems { get; set; }


    }
}

HereToYou/Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace HereToYou.Models
{
	public class Product
	{
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

        public int ProductId { get; set; }
        [MaxLength(255)]
        public string ProductName { get; set; }
        [MaxLength(255)]
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public int Stock { get; set; }
        [NotMapped]
        public IFormFile? ImageFile { get; set; }

        public int? CategoryId { get; set; }
        [ForeignKey("CategoryId")]

        public Category Category { get; set; }
        public ICollection<OrderItem> OrderItems { get; set; }

    }

}

HereToYou/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HereToYou.Context;
using HereToYou.Models;

namespace HereToYou.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly MyContext _context;

        public CategoriesController(MyContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
              return _context.Categories != null ? 
                          View(await _context.Categories.ToListAsync()) :
                          Problem("Entity set 'MyContext.Categories'  is null.");
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            ViewBag.name = HttpContext.Session.GetString("name");

            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Category category)
        {
            //if (ModelState.IsValid)
            //{
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            //}
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'MyContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

HereToYou/Controllers/ContactUsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using HereToYou.Context;
using HereToYou.Models;

namespace ecommerce.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly MyContext _context;

        public ContactUsController(MyContext context)
        {
            _context = context;
        }

        // GET: ContactUs
        public async Task<IActionResult> Index()
        {
            ViewBag.name = HttpContext.Session.GetString("name");
            var myContext = _context.ContactUsMessages.Include(c => c.User);
            return View(await myContext.ToListAsync());
        }

        // GET: ContactUs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ContactUsMessages == null)
            {
                return NotFound();
            }

            var contactUs = await _context.ContactUsMessages
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ContactUsId == id);
            if (contactUs == null)
            {
                return NotFound();
            }

            return View(contactUs);
        }


        // GET: ContactUs/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: ContactUs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Subject,Message,UserId")] ContactUs contactUs)
        {

            _context.Add(contactUs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", contactUs.UserId);
            return View(contactUs);
        }

        // GET: ContactUs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ContactUsMessages == null)
            {
                return NotFound();
            }

            var contactUs = await _context.ContactUsMessages.FindAsync(id);
            if (contactUs == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", contactUs.UserId);
            return View(contactUs);
        }

        // POST: ContactUs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContactUsId,Name,Email,Subject,Message,DateSubmitted,UserId")] ContactUs contactUs)
        {
            if (id != contactUs.UserId)
            {
                return NotFound();
            }


            try
            {
                _context.Update(contactUs);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ContactUsExists((int)contactUs.UserId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "ContactUsId", "ContactUsId", contactUs.UserId);
            return View(contactUs);
        }

        // GET: ContactUs/Delete/5
        // GET: ContactUs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ContactUsMessages == null)
            {
                return NotFound();
            }

            var contactUs = await _context.ContactUsMessages
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.ContactUsId == id);
            if (contactUs == null)
            {
                return NotFound();
            }

            return View(contactUs);
        }

        // POST: ContactUs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contactUs = await _context.ContactUsMessages.FindAsync(id);
            if (contactUs != null)
            {
                _context.ContactUsMessages.Remove(contactUs);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool ContactUsExists(int id)
        {
            return (_context.ContactUsMessages?.Any(e => e.UserId == id)).GetValueOrDefault();
        }
    }
}

HereToYou/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HereToYou.Context;
using HereToYou.Models;

namespace HereToYou.Controllers
{
    public class OrdersController : Controller
    {
        private readonly MyContext _context;

        public OrdersController(MyContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var myContext = _context.Orders.Include(o => o.User);
            return View(await myContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,TotalAmount,CreatedAt,Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,TotalAmount,CreatedAt,Status")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'MyContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

HereToYou/Views/Admin/Category.cshtml
@model IEnumerable<HereToYou.Models.Category>

@{
    ViewData["Title"] = "Index";
    Layout = "AdminLayout";

}
<style>
 
    .primary {
        color: #ffffff !important; /* or any other blue shade you prefer */
        background-color: #ffffff !important;
    }

    /* Update other elements that use the red color */
    .navbar-dark .navbar-nav .nav-link {
        color: #ffffff !important;
    }

    .alert-primary {
        background-color: #ffffff !important;
        border-color: #ffffff !important;
    }

    .progress-bar.progress-bar-striped.bg-primary {
        background-color: #ffffff !important;
    }
</style>
<div style="padding-left:30px;padding-top:25px">

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

HereToYou/Views/Admin/Index.cshtml
@{
    Layout = "AdminLayout";
}
<style>
    /* General Styles */
    body {
        background-color: #191C24;
        color: white;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .container-fluid {
        padding: 1.5rem;
    }

    .bg-primary {
        background-color: #191C24 !important; /* Bright blue */
        color: #ffffff !important;
    }

    .bg-secondary {
        background-color: #191C24 !important; /* Light gray background */
        color: #333;
    }

    .rounded {
/*         border-radius: 0.75rem; /* Rounded corners */
 */    }

    .p-4 {
        padding: 1.5rem; /* Padding */
    }

    /* Header and Alerts */
    .navbar-dark .navbar-nav .nav-link {
        color: #ffffff !important;
    }

    .alert-primary {
        background-color: #191C24 !important; /* Light gray background */
/*         border-color: #007bff !important;
 */        color: #ffffff;
    }

    .progress-bar.bg-primary {
        background-color: #191C24 !important; /* Light gray background */
    }

    /* Cards and Widgets */
    .card {
        background-color: #191C24 !important; /* Light gray background */
/*         border: 1px solid #e1e5eb;
 */        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        transition: box-shadow 0.3s ease;
    }

        .card:hover {
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
        }

        .card .icon {
            font-size: 2rem;
            color: #007bff;
        }

        .card .details {
            margin-left: 1rem;
        }

        .card h6 {
            font-size: 1.25rem;
            margin-bottom: 0.5rem;
        }
    /* Add some spacing and styling to task items */
    .todo-list {
        max-height: 200px;
        overflow-y: auto;
    }

    .task-item {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 8px 0;
        border-bottom: 1px solid #dee2e6;
    }

        .task-item span {
            flex-grow: 1;
            margin-left: 8px;
        }

        .task-item button {
            background: none;
            border: none;
            color: #dc3545;
            cursor: pointer;
        }

    /* Table Styles */
    .table thead th {
        background-color: #191C24 !important; /* Light gray background */
        color: #ffffff;
        border-bottom: 1px solid #0056b3;
    }

    .table tbody tr {
        background-color: #191C24 !important; /* Light gray background */
    }

        .table tbody tr:nth-child(even) {
            background-color: #191C24 !important; /* Light gray background */
        }

        .table tbody tr:hover {
            background-color: #e9ecef; /* Hover effect for rows */
        }

    .table tbody td {
        vertical-align: middle;
    }

    /* Form and Input Styles */
    .form-control {
/*         border: 1px solid #ced4da;
        border-radius: 0.375rem; */
        box-shadow: none;
/*         transition: border-color 0.3s ease;
 */    }

        .form-control:focus {
/*             border-color: #007bff;
 */            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
        }

    .btn-primary {
        background-color: #191C24 !important; /* Light gray background */
/*         border-color: #007bff;
 */        color: #ffffff;
        transition: background-color 0.3s ease, border-color 0.3s ease;
    }

        .btn-primary:hover {
            background-color: #191C24 !important; /* Light gray background */
            border-color: #004085;
        }

    /* Task List Styles */
    .todo-list {
        max-height: 300px;
        overflow-y: auto;
    }

        .todo-list .task-item {
            border-bottom: 1px solid #e1e5eb;
            padding: 0.5rem 0;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

            .todo-list .task-item input[type="checkbox"] {
                margin-right: 1rem;
            }

            .todo-list .task-item span {
                flex-grow: 1;
            }

            .todo-list .task-item button {
                background: none;
                border: none;
                color: #dc3545;
                cursor: pointer;
            }
</style>


<!-- Sale & Revenue Start -->
<div class="container-fluid pt-4">
    <div class="row g-4">
        <div class="col-sm-6 col-xl-3">
            <div class="card d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-line icon"></i>
                <div class="details">
                    <p class="mb-2">Today Sale</p>
                    <h6 class="mb-0">$@ViewBag.LastDaySales</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="card d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-bar icon"></i>
                <div class="details">
                    <p class="mb-2">Total Sale</p>
                    <h6 class="mb-0">$@ViewBag.totalSale</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="card d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-area icon"></i>
                <div class="details">
                    <p class="mb-2">Product Count</p>
                    <h6 class="mb-0">@ViewBag.productsCount</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="card d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-pie icon"></i>
                <div class="details">
                    <p class="mb-2">User Count</p>
                    <h6 class="mb-0">@ViewBag.userCount</h6>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Sale & Revenue End -->
<!-- Widgets Start -->
<div class="container-fluid pt-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-6 col-xl-4">
            <div class="card h-100">
                <div class="d-flex align-items-center justify-content-between p-4">
                    <h6 class="mb-0">Messages</h6>
                    <a asp-controller="ContactUs" asp-action="Index" >Show All</a>
                </div>
                <div class="p-4 todo-list">
                    @if (ViewData["ContactMessages"] != null && ((IEnumerable<HereToYou.Models.ContactUs>)ViewData["ContactMessages"]).Any())
                    {
                        var contactMessages = (IEnumerable<HereToYou.Models.ContactUs>)ViewData["ContactMessages"];

                        foreach (var contact in contactMessages)
                        {
                            <div class="task-item">
                                <input type="checkbox" />
@*                                 <span>Message from: @contact.Name </span>
 *@                                <span>@contact.Message</span>
@*                                 <button><i class="fa fa-times"></i></button>
 *@                            </div>
                        }
                    }
                    else
                    {
                        <p>No messages available.</p>
                    }
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-6 col-xl-4">
            <div class="h-100 bg-secondary rounded p-4">
                <div class="d-flex align-items-center justify-content-between mb-4">
                    <h6 class="mb-0">Calender</h6>
                </div>
                <div id="calender"></div>
            </div>
        </div>

        <div class="col-sm-12 col-md-6 col-xl-4">
            <div class="card h-100">
                <div class="d-flex align-items-center justify-content-between p-4">
                    <h6 class="mb-0">To Do List</h6>
                </div>
                <div class="p-4">
                    <div class="d-flex mb-2">
                        <input id="taskInput" class="form-control  border-0" type="text" placeholder="Enter task" />
                        <button id="addTaskButton" type="button" class="btn btn-primary ms-2">Add</button>
                    </div>
                    <div id="todoList" class="todo-list">
                        <!-- Tasks will be dynamically added here -->
                    </div>
                </div>
            </div>
        </div>

    </div>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const addTaskButton = document.getElementById('addTaskButton');
            const taskInput = document.getElementById('taskInput');
            const todoList = document.getElementById('todoList');

            // Function to create a new task item
            function createTaskItem(taskContent) {
                const taskItem = document.createElement('div');
                taskItem.className = 'task-item';

                const checkbox = document.createElement('input');
                checkbox.className = 'form-check-input m-0';
                checkbox.type = 'checkbox';

                const span = document.createElement('span');
                span.textContent = taskContent;

                const removeButton = document.createElement('button');
                removeButton.innerHTML = '<i class="fa fa-times"></i>';
                removeButton.onclick = () => taskItem.remove();

                taskItem.appendChild(checkbox);
                taskItem.appendChild(span);
                taskItem.appendChild(removeButton);

                return taskItem;
            }

            // Add task on button click
            addTaskButton.addEventListener('click', () => {
                const taskContent = taskInput.value.trim();
                if (taskContent) {
                    const taskItem = createTaskItem(taskContent);
                    todoList.appendChild(taskItem);
                    taskInput.value = ''; // Clear input field
                }
            });

            // Optional: Add task on Enter key press
            taskInput.addEventListener('keypress', (event) => {
                if (event.key === 'Enter') {
                    event.preventDefault();
                    addTaskButton.click();
                }
            });
        });
    </script>

</div>
<!-- Widgets End -->

HereToYou/Views/Admin/Order.cshtml
@model IEnumerable<HereToYou.Models.Order>

@{
    ViewData["Title"] = "Index";
    Layout = "AdminLayout";

}

<style>
    <style >
    .primary {
        color: #ffffff !important; /* or any other blue shade you prefer */
        background-color: #ffffff !important;
    }

    /* Update other elements that use the red color */
    .navbar-dark .navbar-nav .nav-link {
        color: #ffffff !important;
    }

    .alert-primary {
        background-color: #ffffff !important;
        border-color: #ffffff !important;
    }

    .progress-bar.progress-bar-striped.bg-primary {
        background-color: #ffffff !important;
    }
</style>
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalAmount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>